FORMAT: 1A
HOST: http://www.huunu.com

# Huunu
All calls other than `Login` will require the UI to pass an `authorization_token` to the backend.


Remaining TODOS:

`Figure out outcome history call`

`Figure out summary calls`

`Determine if we need a call for FAQ (or is this just hard coded templates?)`

`Do we need a call to update outcome scores / your position every so often? (this would probably only be necessary if we use the full data on GET /questions`



# Group Questions
One option we were discussing over here is to not return all the question data in this call 
(in the case there could be a large amount of questions in the market).

If we think that might be an issue, I propose we change this call to not send any 
data in this call after the `overall_position` key.
When clicking into a question, the UI would then make the next call in this group (`GET /questions/{id}`) and retrieve the remaining data points.
## Questions Collection [/markets/{market_id}/questions]
### List all Questions [GET]
+ Response 200 (application/json)

        {
            "questions": [
                {
                    "id": 1, 
                    "topic": "Technology",
                    "title": "Google Glass", 
                    "description": "Google Glass is a wearable computer with an optical head-mounted display (OHMD) that is being developed by Google in the Project Glass research and development project, with a mission of producing a mass-market ubiquitous computer. Google Glass displays information in a smartphone-like hands-free format, that can communicate with the Internet via natural language voice commands.", 
                    "overall_position": {
                        "direction": "up",
                        "amount": 10
                    },
                    "media": "http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Google_Glass_Explorer_Edition.jpeg/300px-Google_Glass_Explorer_Edition.jpeg", 
                    "outcomes": [
                        { 
                            "id": 23,
                            "name": "Definite winner",
                            "media": "http://reviewrun.net/wp-content/uploads/2013/07/thumbs-up-button-pro.jpg",
                            "score": 70,
                            "position": 6
                        },
                        { 
                            "id": 24,
                            "name": "Losing idea",
                            "media": "http://www.firetheboxingdiva.com/resources/thumbs-down.jpg",
                            "score": 30,
                            "position": null
                        }
                    ]
                }, 
                {
                    "id": 2, 
                    "topic": "Technology",
                    "title": "XBox One vs PS4", 
                    "description": "Which console is better? The Xbox One or the PS4?", 
                    "overall_position": null,
                    "media": "http://media2.policymic.com/0521d359789279d1498bae356cc504a5.jpg", 
                    "outcomes": [
                        { 
                            "id": 25,
                            "name": "XBox One",
                            "media": null,
                            "score": 50,
                            "position": null
                        },
                        { 
                            "id": 26,
                            "name": "PS4",
                            "media": null,
                            "score": 50,
                            "position": null
                        }
                    ]
                }
            ]
        }

## Question [/markets/{market_id}/questions/{id}]
A single Question object with all its details.
This would likely only be used if we decide not to return all data on the **Questions Collection** call.

+ Parameters
    + market_id (required, number, `1`) ... Numeric `id` of the Market to get.
    + id (required, number, `1`) ... Numeric `id` of the Question to get.

### Retrieve a Question [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "topic": "Technology",
                "title": "Google Glass", 
                "description": "Google Glass is a wearable computer with an optical head-mounted display (OHMD) that is being developed by Google in the Project Glass research and development project, with a mission of producing a mass-market ubiquitous computer. Google Glass displays information in a smartphone-like hands-free format, that can communicate with the Internet via natural language voice commands.", 
                "overall_position": {
                    "direction": "up",
                    "amount": 10
                },
                "media": "http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Google_Glass_Explorer_Edition.jpeg/300px-Google_Glass_Explorer_Edition.jpeg", 
                "outcomes": [
                    { 
                        "id": 23,
                        "name": "Definite winner",
                        "media": "http://reviewrun.net/wp-content/uploads/2013/07/thumbs-up-button-pro.jpg",
                        "score": 70,
                        "position": 6
                    },
                    { 
                        "id": 24,
                        "name": "Losing idea",
                        "media": "http://www.firetheboxingdiva.com/resources/thumbs-down.jpg",
                        "score": 30,
                        "position": null
                    }
                ]
            }



# Group Outcome
## Outcome [/markets/{market_id}/outcomes/{outcome_id}]
### Submit a trade [PUT]
+ Parameters
    + market_id (required, number, `1`) ... Numeric `id` of the Market to get.
    + outcome_id (required, number, `1`) ... Numeric `id` of the Outcome to get.

+ Request (application/json)

        { 
            "position": 3, 
            "comment": "Some comment" 
        }
        
+ Response 201 (application/json)

    + Body
    
            {
                
            }


## Outcome History [/markets/{market_id}/questions/{question_id}/outcomes/history]
List of outcomes for a user

+ Parameters
    + market_id (required, number, `1`) ... Numeric `id` of the Market to get.
    + question_id (required, number, `1`) ... Numeric `id` of the Question to get.

### Retrieve an Outcome with History [GET]
+ Response 201 (application/json)

    + Body

            {
                "id": 3,
                "title": "Outcome One",
                "description": "Fusce sed quam sed augue laoreet rutrum in sit amet mi",
                "media": "http://www.huunu.com/assets/lakdfj8.mp4",
                "question_id": 3,
                "overall_position": 12
                "price": {
                    "all": [
                        ['01-May-12', 582.13],
                        ['30-Apr-12', 583.98],
                        ['27-Apr-12', 603.00],
                        ['26-Apr-12', 607.70],
                        ['25-Apr-12', 610.00]
                    ],
                    "user": [
                        ['01-May-12', 582.13],
                        ['30-Apr-12', 583.98],
                        ['27-Apr-12', 603.00],
                        ['26-Apr-12', 607.70],
                        ['25-Apr-12', 610.00]
                    ]
                ] 
            },
            {
                "id": 4,
                "title": "Outcome Two",
                "description": "Fusce sed quam sed augue laoreet rutrum in sit amet mi",
                "media": "http://www.huunu.com/assets/lakdfj8.mp4",
                "question_id": 3,
                "overall_position": -4
                "price": {
                    "all": [
                        ['01-May-12', 582.13],
                        ['30-Apr-12', 583.98],
                        ['27-Apr-12', 603.00],
                        ['26-Apr-12', 607.70],
                        ['25-Apr-12', 610.00]
                    ],
                    "user": [
                        ['01-May-12', 582.13],
                        ['30-Apr-12', 583.98],
                        ['27-Apr-12', 603.00],
                        ['26-Apr-12', 607.70],
                        ['25-Apr-12', 610.00]
                    ]
                ] 
            }



# Group Badges
## Badges Collection [/markets/{market_id}/badges]
An array of Badge objects belonging to the User (identified by authorization token sent with call).
### List all Badges [GET]
This endpoint will be hit whenever performing an action that may trigger the user to gain a badge, and once upon logging in.

+ Response 200 (application/json)

        {
            "badges": [
                { 
                    "id": 1, 
                    "title": "Explorer", 
                    "description": "blah blah", 
                    "artwork": "http://www.huunu.com/assets/lakdfj8.svg" 
                },
                { 
                    "id": 2, 
                    "title": "Trailblazer", 
                    "description": "blah blah", 
                    "artwork": "http://www.huunu.com/assets/lakdfj1.svg" 
                }
            ]
        }

## Badge [/markets/{market_id}/badges/{id}]
A single Badge object with all its details. 

Thinking about this more, I'm not sure we need this call. We will already have all necessary information from the `GET /badges` call. Leaving this in for now though.

+ Parameters
    + id (required, number, `3`) ... Numeric `id` of the Question to perform action with.

### Retrieve a Badge [GET]
+ Response 200 (application/json)

    + Body

            { 
                "id": 1, 
                "title": "Explorer", 
                "description": "blah blah", 
                "artwork": "http://www.huunu.com/assets/lakdfj8.svg" 
            }



# Group Users
## Users Collection [/users/{id}]
### Update a User [PUT]
This call is only used when updating a user's account information.

+ Request (application/json)

        { 
            "username": "jvowell", 
            "email": "jvowell@consensuspoint.com",
            "email_preference": false,
            "new_password": "jhasdfsadfs",
            "old_password": "jhsv8ch3idhj"
        }

+ Parameters
    + username (required, string, `jvowell`) ... Username
    + email (required, string, `jvowell@consensuspoint.com`) ... User's Email
    + email_preference (required, boolean, `true`) ... Subscribe to market emails
    + old_password (optional, string, `jhsv8ch3idhj`) ... Old Password (only required if updating password)
    + password (optional, string, `jhasdfsadfs`) ... Password (only required if updating password)

+ Response 201 (application/json)

        { 
            "username": "jvowell", 
            "email": "jvowell@consensuspoint.com",
            "email_preference": false
        }


### Retrieve a User [GET]
Used for populating the user account information.
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to retrieve.

+ Response 200 (application/json)

    + Body

            { 
                "username": "jvowell", 
                "email": "jvowell@consensuspoint.com",
                "email_preference": false
            }
        

# Group Authentication

## Login [/login]
Returns the `authorization_token` that is used for all other calls.
Also returns the user's `balance`.

### Login [POST]
+ Request (application/json)

        { 
            "username": "jvowell", 
            "password": "askdjfhAsdf"
        }

+ Response 201 (application/json)

        { 
            "authorization_token": "asdjhfahsfbq35askhdfbauydsbf78345sdf",
            "market_id": 412,
            "balance": 50 
        }

## Logout [/logout]
### Logout [GET]
+ Response 200




# Group Demographics
## Demographics [/markets/{market_id}/demographics]
### Retrieve Demographic Questions [GET]
+ Response 200 (application/json)

    + Body
    
            { 
                "questions": [
                    { 
                        "id": 9, 
                        "text": "What does the fox say?", 
                        "options": [
                            { "id": 3, "text": "Ring-ding-ding" },
                            { "id": 4, "text": "Heidi-heidi-heidi-ho" },
                            { "id": 5, "text": "Chaka-chaka-cho" }
                        ]
                    },
                    { 
                        "id": 10, 
                        "text": "What does the cow say?", 
                        "options": [
                            { "id": 6, "text": "Ring-ding-ding" },
                            { "id": 7, "text": "Heidi-heidi-heidi-ho" },
                            { "id": 8, "text": "Chaka-chaka-cho" }
                        ]
                    }
                ]
            }

### Post demographic answers [POST]
+ Request (application/json)

        { 
            "answers": [
                { "question_id": 9, "answer_id": 5 },
                { "question_id": 12, "answer_id": 33 }
            ]
        }


+ Response 201 


# Group Summary
## Summary [/markets/{market_id}/summary]
### Retrieve Summary data [GET]
+ Response 200 (application/json)

        {
            "overall_score": 23,
            "viewed": {
                "count": 8,
                "current_user": 30,
                "all_users": 60,
            },
            "commented": {
                "count": 5,
                "current_user": 40,
                "all_users": 70
            }
        }